language: ruby
rvm:
- 2.3.0
env:
- APIKEY="20808d88a8662cb38a3b08e4a729a404"
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: Gcn6bRhLZoafCLiv2I8uEyXNGPlspnFQ07kZbj9aClqUC1UF1NxhGAq9Z09yQZofeCT46694f5r7zxK1iGUz2jV1jFTYkR5ryw1skybDnrYE0gUqx9pOlq44+wV500CZ/SD5C/OCCePDYK65vsnjXD30YlMB/7zTvUndMY4HplBH62JF8qPXeq545vZfbiFNwjYSwm/3tCdSKELMYklKJpZutEWTOYBXP7azKILFxQwlg+aYW8x9w3dXe7vZFV0h8D3U2KlXD+M5voVIdfcs63BIuyU2sMsXkJ9F3NrzjMwt42IirPZRyTo5TRF5AQQdTnHS5yzNSamAbXEWnOWG+iHn2921IppOKHQalxsbbM5A+Q+ogba2eFkf1PaxpGnrggDY0TUsFYA6U0nnUQJxySIJKjbtD1GodfpDyrgvFMlNOWT1fNm65dEhxMfmWRoGYR4ciNoXvJptCXKeZl+9DbkJR4Ilz75JLbOYAy26n94jjSZZUxOmEME1aJ0jmM1gY+pQ5ATj/8+rXTPOg1IvFcH3VQFNd0j/cQHnQxz9S3t0jJVdZBfd02SjbJ6dbnWuMe/vvVtXPeRQQ33kTdLKZ3RRVrZHeVfZ5aQu6fQqDd0HqJ4kouPQkjbCHJ/jPXjBqohjcy8x4FRRQPCtox3jrrYH8wOrds5DGpjKj8dUZ8s=
  app: cryptic-island-26658
  run: "rake db:migrate"
  on:
    repo: iilumme/wadror
